variable "profile_name" {}
variable "vpc_cidr_range" {}
variable "project" {}
variable "public_subnet_cidr" {}
variable "public_subnet_cidr-2" {}
variable "instace_type" {}
variable "desired_capacity" {}
variable "min_size" {}
variable "max_size" {}
